### ISSUE TITLE
Send request button not Working

### ISSUE THREAD

**Issue by viettbq2002** [zer0five/yomikaze#1]
# Nút send request không hoạt động
**ID 0001**
**Description:**  Nút send request không hoạt, không hiện popup khi nhấn , lỗi code javascript hoặc thymeleaf link 
**Status:**  new
**Priority:**  high
**Assignee:**   Project mangment
**Bug Severity:**   High
## Steps to reproduce the issue
1. chạy project
2. truy cập localhost:8080/login
3. nhập tài khoản admin , mật khẩu admin
4. try cập localhost:8080/request
5. nhấn nút send request, không hoạt động
## screenshot
![image](https://user-images.githubusercontent.com/98259617/196135249-410a8e29-8a42-42aa-9227-249ccc44c96e.png)
## code
     <meta charset="UTF-8">  
     <meta http-equiv="X-UA-Compatible" content="IE=edge">  
     <meta name="viewport" content="width=device-width, initial-scale=1.0">  
      
      
      
      
      
      
      
      
      
      <script defer th:src="@{/asset/js/alpine.min.js}"></script>  
     <script th:src="@{/asset/js/feather.min.js}"></script>  
     <link rel="stylesheet" th:href="@{/asset/css/tailwind.css}"/>  
     <title>Request Management</title>  
    </head>

**Comment by K4zoku** [comment]
Đã sửa
